// <auto-generated />
using System;
using Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(ContextoDb))]
    partial class ContextoDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Business.Modelos.Leitura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CodCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("codigo_cliente");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_leitura");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("latitude");

                    b.Property<long>("LeituraAnterior")
                        .HasColumnType("bigint")
                        .HasColumnName("leitura_anterior");

                    b.Property<long?>("LeituraAtual")
                        .HasColumnType("bigint")
                        .HasColumnName("leitura_atual");

                    b.Property<long>("LeituristaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_ leiturista");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("longitude");

                    b.Property<long>("OcorrenciaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_ocorrencia");

                    b.HasKey("Id");

                    b.HasIndex("LeituristaId");

                    b.HasIndex("OcorrenciaId");

                    b.ToTable("tbl_leituras");
                });

            modelBuilder.Entity("Business.Modelos.Leiturista", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<long>("Matricula")
                        .HasColumnType("bigint")
                        .HasColumnName("matricula");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("tbl_leituristas");
                });

            modelBuilder.Entity("Business.Modelos.Ocorrencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("descricao");

                    b.Property<bool>("PermiteLeitura")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("permite_leitura");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("tbl_ocorrencias");
                });

            modelBuilder.Entity("Business.Modelos.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("email");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("funcao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.ToTable("tbl_usuarios");
                });

            modelBuilder.Entity("Business.Modelos.Leitura", b =>
                {
                    b.HasOne("Business.Modelos.Leiturista", "Leiturista")
                        .WithMany("Leituras")
                        .HasForeignKey("LeituristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Business.Modelos.Ocorrencia", "Ocorrencia")
                        .WithMany("Leituras")
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Leiturista");

                    b.Navigation("Ocorrencia");
                });

            modelBuilder.Entity("Business.Modelos.Leiturista", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("Business.Modelos.Ocorrencia", b =>
                {
                    b.Navigation("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
